Implementación del BOA (Comunidad Autónoma de Aragón)
bukosabino/justicio pull request #79
Opened 2024-03-14 07:20 UTC by ngarce

Implemento la ETL del BOA siguiendo los estándares comunes al resto de boletines. 

Este scraper tiene una particularidad: a partir de una fecha dada, se puede obtener una url que devuelve todos los boletines completos, con sus metadatos correspondientes, de una vez (véase la clase BOAScrapper y el README). Por lo tanto, no es necesaria una función download_documents(url), dado que  no accedemos a los documentos uno a uno. Es por eso que he escrito el método download_documents vacío, ya que la clase hereda de BaseScrapper y tenía que incluirlo igualmente (creo).

Lo he probado en local y se integra en el programa sin errores:

`python -m src.etls.boa.load dates 2024/01/01 2024/01/31`

2024-03-18 21:53 UTC, ntkog requested changes

2024-03-18 21:53 UTC, ntkog commented on src/etls/boa/scrapper.py
> +    def download_document(self, url: str) -> MetadataDocument:
@ngarce , échale un ojo a esta [explicación](https://github.com/bukosabino/justicio/pull/76#discussion_r1523848194)

Ahí se explica el por qué implementar dowload_document

2024-03-18 21:53 UTC, ntkog commented on src/etls/boa/README.md
> +"Texto" : "<br/>
Ojo, con que en texto se cuelen etiquetas HTML. El texto luego se va a convertir en un embedding, y a la hora de tokenizarlo, puede afectar a la calidad del embedding.

Como recomendación, intenta que el texto sea texto plano, sin marcado.

2024-03-18 21:53 UTC, ntkog commented on src/etls/boa/scrapper.py
> +                clean_text = content.replace('<br/>', '')
Si puedes comprueba que a parte de  <br/> 's , no se cuelen ni HTML entities , ni otras etiquetas:
```python
from lxml import etree
def remove_html_tags(text):
    parser = etree.HTMLParser()
    tree = etree.fromstring(text, parser)
    return etree.tostring(tree, encoding="unicode", method='text')  

plan_text = remove_html_tags(html_string) 
print(plan_text.strip()) 
```

2024-03-19 17:33 UTC, ntkog commented on src/etls/boa/scrapper.py
> +    def download_document(self, url: str) -> MetadataDocument:
Se me ocurre una solución de compromiso:

Desde tu BOAScrapper puedes:

iterar sobre el json con todos los documentos, llamando así al download_document:

https://github.com/bukosabino/justicio/blob/d510571dc45248cf658731bcfe5a2a47fa227b99/src/etls/boe/scrapper.py#L131

dentro de download_document omites los requests (porque  las peticiones  ya las has hecho antes).

Así digamos que preservamos la consistencia entre ETL's y tampoco cambiamos mucho tu código original.

¿Qué te parece?

2024-03-19 17:55 UTC, ngarce commented on src/etls/boa/scrapper.py
> +    def download_document(self, url: str) -> MetadataDocument:
Perfecto!

2024-03-19 18:03 UTC, ngarce commented on src/etls/boa/scrapper.py
> +                clean_text = content.replace('<br/>', '')
Lo comprobé con los documentos de varios días y no había más que `<br/>`'s, pero casi mejor incluyo ese código por si acaso, con eso ya valdría, ¿no?

2024-03-21 09:06 UTC, ntkog commented
Comparando colecciones, me he encontrado esto, (son detalles menores, pero si tenemos un formato consistente mejor) . Idealmente el formato "rector" es el de la collección del BOE:
![Screenshot_20240321_095801](https://github.com/bukosabino/justicio/assets/1333901/42731b36-eccd-42f5-a028-e741c2a695ee)

2024-03-21 16:00 UTC, ntkog commented
LGTM, buen trabajo @ngarce . @bukosabino , mergeamos?

2024-03-21 17:47 UTC, bukosabino reviewed
Refactor code

2024-03-21 17:47 UTC, bukosabino commented on src/etls/boa/scrapper.py
> +        fecha_disposicion = fecha_disp_raw[0:4]+"-"+fecha_disp_raw[4:6]+"-"+fecha_disp_raw[6:8]
```suggestion
        fecha_disposicion = datetime.strptime(doc["Fechadisposicion"], "%Y%m%d").strftime("%Y-%m-%d")
```

2024-03-21 21:17 UTC, ngarce commented
Hecho, @bukosabino

2024-03-22 19:03 UTC, merged